# camos a construir los contenedores de manera mas vacana

#creado version
version: '3.9'

#creado servicio (o contenedor)
services:
  chanchito: # el ejecutable el Dockerfile que esta en root
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "3001:3001" # si queremos exponer mas puertos
    links:
      - monguito # nombre del contenedor
    volumes:
      - .:/home/app # montar el volumen de la carpeta actual en la carpeta /home/app del contenedor (podremos ver los cambios en tiempo real)

  monguito:
    image: mongo # nombre de la imagen
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nico
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      # where does mongodb store data? (GOOGLE IT)
      - mongo-data:/data/db # debemos decirle donde sera montando el volumen en el contenedor
      # mysql -> /var/lib/mysql
      # postgresql -> /var/lib/postgresql/data
      # sqlserver -> /var/opt/mssql/data

# definir volumenes
volumes:
  mongo-data: